In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('ageincome.csv')

In [3]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [6]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [7]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [8]:
df.isnull()

     CustomerID  Gender    Age  Annual Income (k$)  Spending Score (1-100)
0         False   False  False               False                   False
1         False   False  False               False                   False
2         False   False  False               False                   False
3         False   False  False               False                   False
4         False   False  False               False                   False
..          ...     ...    ...                 ...                     ...
195       False   False  False               False                   False
196       False   False  False               False                   False
197       False   False  False               False                   False
198       False   False  False               False                   False
199       False   False  False               False                   False

[200 rows x 5 columns]

In [9]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [10]:
df.dtypes

CustomerID                 int64
Gender                    object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [12]:
renamed = df.rename(columns={'Annual Income (k$)' : 'Income'}, inplace=True)

In [13]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Income', 'Spending Score (1-100)'], dtype='object')

In [14]:
df.pop('CustomerID')#if u have this colum ,i u want to pop
df.pop('Spending Score (1-100)')#if u have this colum ,i u want to pop

0      39
1      81
2       6
3      77
4      40
       ..
195    79
196    28
197    74
198    18
199    83
Name: Spending Score (1-100), Length: 200, dtype: int64

In [15]:
df

     Gender  Age  Income
0      Male   19      15
1      Male   21      15
2    Female   20      16
3    Female   23      16
4    Female   31      17
..      ...  ...     ...
195  Female   35     120
196  Female   45     126
197    Male   32     126
198    Male   32     137
199    Male   30     137

[200 rows x 3 columns]

In [16]:
df['Income'].mean()

60.56

In [18]:
df['Age'].max()

70

In [20]:
df['Income'].std()

26.264721165271254

In [21]:
df['Income'].mean()

60.56

In [22]:
df['Age'].min()

18

In [23]:
df['Age'].median()

36.0

In [24]:
df.groupby(['Age']).count()

     Gender  Income
Age
18        4       4
19        8       8
20        5       5
21        5       5
22        3       3
23        6       6
24        4       4
25        3       3
26        2       2
27        6       6
28        4       4
29        5       5
30        7       7
31        8       8
32       11      11
33        3       3
34        5       5
35        9       9
36        6       6
37        3       3
38        6       6
39        3       3
40        6       6
41        2       2
42        2       2
43        3       3
44        2       2
45        3       3
46        3       3
47        6       6
48        5       5
49        7       7
50        5       5
51        2       2
52        2       2
53        2       2
54        4       4
55        1       1
56        1       1
57        2       2
58        2       2
59        4       4
60        3       3
63        2       2
64        1       1
65        2       2
66        2       2
67        4       4
68        3       3
69        1       1
70        2       2

In [25]:
df.groupby(['Gender']).count()

        Age  Income
Gender
Female  112     112
Male     88      88

In [27]:
df[['Age' , 'Income']].mode()

    Age  Income
0  32.0      54
1   NaN      78

In [29]:
df.groupby(['Gender'])['Age'].mean()

Gender
Female    38.098214
Male      39.806818
Name: Age, dtype: float64

In [33]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df

     Gender  Age  Income
0         1   19      15
1         1   21      15
2         0   20      16
3         0   23      16
4         0   31      17
..      ...  ...     ...
195       0   35     120
196       0   45     126
197       1   32     126
198       1   32     137
199       1   30     137

[200 rows x 3 columns]

In [34]:
df.groupby(['Gender'])['Age'].mean()

Gender
0    38.098214
1    39.806818
Name: Age, dtype: float64

In [35]:
grouped = df.groupby('Age')['Income'].describe()
grouped

     count        mean        std   min     25%    50%     75%    max
Age
18     4.0   51.250000  14.056434  33.0   44.25   53.5   60.50   65.0
19     8.0   57.000000  20.632845  15.0   47.50   63.5   67.25   81.0
20     5.0   41.600000  24.815318  16.0   21.00   37.0   61.00   73.0
21     5.0   38.800000  19.018412  15.0   30.00   33.0   54.00   62.0
22     3.0   31.333333  22.278540  17.0   18.50   20.0   38.50   57.0
23     6.0   41.500000  23.441416  16.0   20.75   41.5   60.00   70.0
24     4.0   39.250000  16.357975  20.0   33.50   38.5   44.25   60.0
25     3.0   57.666667  29.263174  24.0   48.00   72.0   74.50   77.0
26     2.0   58.000000   5.656854  54.0   56.00   58.0   60.00   62.0
27     6.0   63.166667  18.400181  40.0   49.50   63.5   75.25   88.0
28     4.0   85.250000  11.615363  76.0   76.75   82.0   90.50  101.0
29     5.0   63.600000  28.866936  28.0   40.00   73.0   79.00   98.0
30     7.0   76.142857  39.612408  19.0   56.00   78.0   93.50  137.0
31     8.0   48.375000  23.323425  17.0   35.50   41.5   70.50   81.0
32    11.0   87.181818  26.809768  48.0   74.00   77.0  100.00  137.0
33     3.0   80.333333  35.837597  42.0   64.00   86.0   99.50  113.0
34     5.0   79.000000  15.968719  58.0   78.00   78.0   78.00  103.0
35     9.0   46.666667  38.632888  18.0   21.00   24.0   74.00  120.0
36     6.0   81.000000  22.556595  37.0   85.50   87.0   87.00  103.0
37     3.0   65.000000  40.112342  20.0   49.00   78.0   87.50   97.0
38     6.0   74.500000  20.462160  54.0   64.75   69.0   76.25  113.0
39     3.0   72.666667   4.725816  69.0   70.00   71.0   74.50   78.0
40     6.0   61.666667  19.551641  29.0   55.50   64.5   70.50   87.0
41     2.0  101.000000   2.828427  99.0  100.00  101.0  102.00  103.0
42     2.0   60.000000  36.769553  34.0   47.00   60.0   73.00   86.0
43     3.0   65.666667  15.695010  48.0   59.50   71.0   74.50   78.0
44     2.0   75.500000   3.535534  73.0   74.25   75.5   76.75   78.0
45     3.0   69.333333  50.767444  28.0   41.00   54.0   90.00  126.0
46     3.0   59.000000  36.755952  25.0   39.50   54.0   76.00   98.0
47     6.0   70.166667  27.694163  43.0   51.75   65.5   76.25  120.0
48     5.0   58.200000  13.700365  39.0   54.00   60.0   61.00   77.0
49     7.0   51.000000  12.884099  33.0   40.50   54.0   62.00   65.0
50     5.0   58.600000  18.420098  40.0   43.00   58.0   67.00   85.0
51     2.0   55.500000  16.263456  44.0   49.75   55.5   61.25   67.0
52     2.0   55.500000  45.961941  23.0   39.25   55.5   71.75   88.0
53     2.0   39.500000   9.192388  33.0   36.25   39.5   42.75   46.0
54     4.0   59.750000  30.998656  28.0   42.25   55.0   72.50  101.0
55     1.0   57.000000        NaN  57.0   57.00   57.0   57.00   57.0
56     1.0   79.000000        NaN  79.0   79.00   79.0   79.00   79.0
57     2.0   64.500000  14.849242  54.0   59.25   64.5   69.75   75.0
58     2.0   54.000000  48.083261  20.0   37.00   54.0   71.00   88.0
59     4.0   65.250000  21.792583  43.0   51.25   62.5   76.50   93.0
60     3.0   43.333333  11.547005  30.0   40.00   50.0   50.00   50.0
63     2.0   56.500000  12.020815  48.0   52.25   56.5   60.75   65.0
64     1.0   19.000000        NaN  19.0   19.00   19.0   19.00   19.0
65     2.0   50.500000  17.677670  38.0   44.25   50.5   56.75   63.0
66     2.0   63.000000   0.000000  63.0   63.00   63.0   63.00   63.0
67     4.0   45.500000  18.699376  19.0   40.00   50.5   56.00   62.0
68     3.0   56.666667   7.767453  48.0   53.50   59.0   61.00   63.0
69     1.0   44.000000        NaN  44.0   44.00   44.0   44.00   44.0
70     2.0   47.500000   2.121320  46.0   46.75   47.5   48.25   49.0

In [36]:
#df.loc[df['Age'] < 25, 'Group'] = 'Teenager'
#df.loc[df['Age'] >= 25, 'Group'] = 'Adult'
#df.loc[df['Age'] >= 65, 'Group'] = 'Senior'

#teen = df['Group']== 'Teenager'
#adult = df['Group']== 'Adult'
#senior = df['Group']== 'Senior'

#print("Income earned by Teenagers")
#df[teen].describe()

Income earned by Teenagers

          Gender        Age     Income
count  35.000000  35.000000  35.000000
mean    0.457143  20.828571  44.657143
std     0.505433   1.992423  20.541125
min     0.000000  18.000000  15.000000
25%     0.000000  19.000000  25.000000
50%     0.000000  21.000000  48.000000
75%     1.000000  23.000000  62.000000
max     1.000000  24.000000  81.000000

In [40]:
data=pd.read_csv('iris (1).csv')

In [41]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [43]:
data.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [44]:
data.info

<bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [45]:
data.shape

(150, 5)

In [48]:
data.groupby(['species'])['petal_length'].mean()

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length, dtype: float64

In [50]:
data.groupby(['species'])['petal_length'].median()

species
setosa        1.50
versicolor    4.35
virginica     5.55
Name: petal_length, dtype: float64

In [53]:
data.groupby(['species'])['sepal_length'].std()

species
setosa        0.352490
versicolor    0.516171
virginica     0.635880
Name: sepal_length, dtype: float64

In [56]:
sort1=sorted(data['sepal_length'])
np.percentile(sort1,25)

5.1

In [57]:
sort1=sorted(data['petal_length'])
np.percentile(sort1,25)

1.6

In [59]:
#optional.....................
setosa = data['species'] == 'setosa'
virginica = data['species'] == 'virginica'
versicolor = data['species'] == 'versicolor'
# Displaying the statistical details for each species
print("Statistics for Iris-setosa:")
print(setosa)

print("\nStatistics for Iris-versicolor:")
print(versicolor)

print("\nStatistics for Iris-virginica:")
print(virginica)

Statistics for Iris-setosa:
0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: species, Length: 150, dtype: bool

Statistics for Iris-versicolor:
0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: species, Length: 150, dtype: bool

Statistics for Iris-virginica:
0      False
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149     True
Name: species, Length: 150, dtype: bool

In [61]:
# Calculate percentiles, mean, and standard deviation
percentiles = data.groupby('species').quantile([0.25, 0.5, 0.75])
means = data.groupby('species').mean()
std_devs = data.groupby('species').std()

print("\nPercentiles:")
print(percentiles)

print("\nMean Values:")
print(means)

print("\nStandard Deviations:")
print(std_devs)

Percentiles:
                 sepal_length  sepal_width  petal_length  petal_width
species
setosa     0.25         4.800        3.200         1.400          0.2
           0.50         5.000        3.400         1.500          0.2
           0.75         5.200        3.675         1.575          0.3
versicolor 0.25         5.600        2.525         4.000          1.2
           0.50         5.900        2.800         4.350          1.3
           0.75         6.300        3.000         4.600          1.5
virginica  0.25         6.225        2.800         5.100          1.8
           0.50         6.500        3.000         5.550          2.0
           0.75         6.900        3.175         5.875          2.3

Mean Values:
            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

Standard Deviations:
            sepal_length  sepal_width  petal_length  petal_width
species
setosa          0.352490     0.379064      0.173664     0.105386
versicolor      0.516171     0.313798      0.469911     0.197753
virginica       0.635880     0.322497      0.551895     0.274650